-- Generated by `python -m workshop render-sql` from workshop/contracts.py.
-- Do not edit by hand. Target: Azure SQL Database (workshop source systems).
-- Safe to re-run: objects are created only when missing.

SET NOCOUNT ON;
GO

IF SCHEMA_ID(N'ctl') IS NULL EXEC(N'CREATE SCHEMA [ctl]');
GO
IF SCHEMA_ID(N'ref') IS NULL EXEC(N'CREATE SCHEMA [ref]');
GO
IF SCHEMA_ID(N'src_dz') IS NULL EXEC(N'CREATE SCHEMA [src_dz]');
GO
IF SCHEMA_ID(N'src_iq') IS NULL EXEC(N'CREATE SCHEMA [src_iq]');
GO
IF SCHEMA_ID(N'src_my') IS NULL EXEC(N'CREATE SCHEMA [src_my]');
GO

-- Country registry (SNAPSHOT)
IF OBJECT_ID(N'ref.country', N'U') IS NULL
CREATE TABLE [ref].[country] (
    [batch_id] varchar(10) NOT NULL,
    [country_id] varchar(2) NOT NULL,
    [country_name] varchar(100) NOT NULL,
    CONSTRAINT [PK_ref_country] PRIMARY KEY ([batch_id], [country_id])
);
GO

-- Operator and partner registry (SNAPSHOT)
IF OBJECT_ID(N'ref.business_associate', N'U') IS NULL
CREATE TABLE [ref].[business_associate] (
    [batch_id] varchar(10) NOT NULL,
    [ba_id] varchar(20) NOT NULL,
    [ba_name] varchar(100) NOT NULL,
    [ba_role] varchar(30) NOT NULL,
    CONSTRAINT [PK_ref_business_associate] PRIMARY KEY ([batch_id], [ba_id])
);
GO

-- Field (asset) registry (SNAPSHOT)
IF OBJECT_ID(N'ref.field', N'U') IS NULL
CREATE TABLE [ref].[field] (
    [batch_id] varchar(10) NOT NULL,
    [field_id] varchar(10) NOT NULL,
    [country_id] varchar(2) NOT NULL,
    [field_name] varchar(100) NOT NULL,
    CONSTRAINT [PK_ref_field] PRIMARY KEY ([batch_id], [field_id])
);
GO

-- Facility registry (SNAPSHOT)
IF OBJECT_ID(N'ref.facility', N'U') IS NULL
CREATE TABLE [ref].[facility] (
    [batch_id] varchar(10) NOT NULL,
    [facility_id] varchar(20) NOT NULL,
    [field_id] varchar(10) NOT NULL,
    [facility_name] varchar(100) NOT NULL,
    CONSTRAINT [PK_ref_facility] PRIMARY KEY ([batch_id], [facility_id])
);
GO

-- Equipment registry (SNAPSHOT)
IF OBJECT_ID(N'ref.equipment', N'U') IS NULL
CREATE TABLE [ref].[equipment] (
    [batch_id] varchar(10) NOT NULL,
    [equipment_id] varchar(20) NOT NULL,
    [facility_id] varchar(20) NOT NULL,
    [equipment_name] varchar(100) NOT NULL,
    [equipment_type] varchar(40) NOT NULL,
    CONSTRAINT [PK_ref_equipment] PRIMARY KEY ([batch_id], [equipment_id])
);
GO

-- Golden well registry (SNAPSHOT)
IF OBJECT_ID(N'ref.well', N'U') IS NULL
CREATE TABLE [ref].[well] (
    [batch_id] varchar(10) NOT NULL,
    [well_id] varchar(20) NOT NULL,
    [field_id] varchar(10) NOT NULL,
    [well_name] varchar(100) NOT NULL,
    [well_status] varchar(20) NOT NULL,
    CONSTRAINT [PK_ref_well] PRIMARY KEY ([batch_id], [well_id])
);
GO

-- Wellbore registry (SNAPSHOT)
IF OBJECT_ID(N'ref.wellbore', N'U') IS NULL
CREATE TABLE [ref].[wellbore] (
    [batch_id] varchar(10) NOT NULL,
    [wellbore_id] varchar(30) NOT NULL,
    [well_id] varchar(20) NOT NULL,
    [wellbore_name] varchar(100) NOT NULL,
    CONSTRAINT [PK_ref_wellbore] PRIMARY KEY ([batch_id], [wellbore_id])
);
GO

-- Completion registry (SNAPSHOT)
IF OBJECT_ID(N'ref.well_completion', N'U') IS NULL
CREATE TABLE [ref].[well_completion] (
    [batch_id] varchar(10) NOT NULL,
    [completion_id] varchar(40) NOT NULL,
    [wellbore_id] varchar(30) NOT NULL,
    [stream_id] varchar(30) NOT NULL,
    [completion_name] varchar(100) NOT NULL,
    CONSTRAINT [PK_ref_well_completion] PRIMARY KEY ([batch_id], [completion_id])
);
GO

-- Production reporting stream registry (SNAPSHOT)
IF OBJECT_ID(N'ref.reporting_stream', N'U') IS NULL
CREATE TABLE [ref].[reporting_stream] (
    [batch_id] varchar(10) NOT NULL,
    [stream_id] varchar(30) NOT NULL,
    [well_id] varchar(20) NOT NULL,
    [stream_name] varchar(100) NOT NULL,
    CONSTRAINT [PK_ref_reporting_stream] PRIMARY KEY ([batch_id], [stream_id])
);
GO

-- Source identifier crosswalk (SNAPSHOT)
IF OBJECT_ID(N'ref.well_alias', N'U') IS NULL
CREATE TABLE [ref].[well_alias] (
    [batch_id] varchar(10) NOT NULL,
    [source_system] varchar(30) NOT NULL,
    [source_well_id] varchar(30) NOT NULL,
    [well_id] varchar(20) NOT NULL,
    CONSTRAINT [PK_ref_well_alias] PRIMARY KEY ([batch_id], [source_system], [source_well_id])
);
GO

-- Unit conversion and BOE factors (SNAPSHOT)
IF OBJECT_ID(N'ref.uom_conversion', N'U') IS NULL
CREATE TABLE [ref].[uom_conversion] (
    [batch_id] varchar(10) NOT NULL,
    [commodity] varchar(10) NOT NULL,
    [uom] varchar(20) NOT NULL,
    [standard_uom] varchar(10) NOT NULL,
    [to_standard_factor] decimal(18,9) NOT NULL,
    [boe_divisor] decimal(9,3) NULL,
    [factor_version] varchar(20) NOT NULL,
    CONSTRAINT [PK_ref_uom_conversion] PRIMARY KEY ([batch_id], [commodity], [uom])
);
GO

-- Effective-dated working interest register (SNAPSHOT)
IF OBJECT_ID(N'ref.working_interest', N'U') IS NULL
CREATE TABLE [ref].[working_interest] (
    [batch_id] varchar(10) NOT NULL,
    [field_id] varchar(10) NOT NULL,
    [valid_from] date NOT NULL,
    [valid_to] date NOT NULL,
    [operator_ba_id] varchar(20) NOT NULL,
    [wi_share] decimal(9,6) NOT NULL,
    [agreement_ref] varchar(30) NOT NULL,
    CONSTRAINT [PK_ref_working_interest] PRIMARY KEY ([batch_id], [field_id], [valid_from])
);
GO

-- Approved RKAP target snapshot (SNAPSHOT)
IF OBJECT_ID(N'ref.target_monthly', N'U') IS NULL
CREATE TABLE [ref].[target_monthly] (
    [batch_id] varchar(10) NOT NULL,
    [field_id] varchar(10) NOT NULL,
    [commodity] varchar(10) NOT NULL,
    [scenario_id] varchar(20) NOT NULL,
    [target_year] int NOT NULL,
    [m01] decimal(19,6) NOT NULL,
    [m02] decimal(19,6) NOT NULL,
    [m03] decimal(19,6) NOT NULL,
    [m04] decimal(19,6) NOT NULL,
    [m05] decimal(19,6) NOT NULL,
    [m06] decimal(19,6) NOT NULL,
    [m07] decimal(19,6) NOT NULL,
    [m08] decimal(19,6) NOT NULL,
    [m09] decimal(19,6) NOT NULL,
    [m10] decimal(19,6) NOT NULL,
    [m11] decimal(19,6) NOT NULL,
    [m12] decimal(19,6) NOT NULL,
    [target_uom] varchar(10) NOT NULL,
    CONSTRAINT [PK_ref_target_monthly] PRIMARY KEY ([batch_id], [field_id], [commodity], [scenario_id], [target_year])
);
GO

-- Finance closing operating cost (SNAPSHOT)
IF OBJECT_ID(N'ref.operating_cost', N'U') IS NULL
CREATE TABLE [ref].[operating_cost] (
    [batch_id] varchar(10) NOT NULL,
    [cost_id] varchar(30) NOT NULL,
    [field_id] varchar(10) NOT NULL,
    [month_start] date NOT NULL,
    [cost_category] varchar(30) NOT NULL,
    [currency_code] varchar(3) NOT NULL,
    [amount_local] decimal(19,4) NOT NULL,
    [closing_status] varchar(20) NOT NULL,
    CONSTRAINT [PK_ref_operating_cost] PRIMARY KEY ([batch_id], [cost_id])
);
GO

-- Approved FX rates (SNAPSHOT)
IF OBJECT_ID(N'ref.fx_rate', N'U') IS NULL
CREATE TABLE [ref].[fx_rate] (
    [batch_id] varchar(10) NOT NULL,
    [valid_on] date NOT NULL,
    [currency_code] varchar(3) NOT NULL,
    [usd_per_unit] decimal(18,9) NOT NULL,
    CONSTRAINT [PK_ref_fx_rate] PRIMARY KEY ([batch_id], [valid_on], [currency_code])
);
GO

-- Indicative price deck (SNAPSHOT)
IF OBJECT_ID(N'ref.price', N'U') IS NULL
CREATE TABLE [ref].[price] (
    [batch_id] varchar(10) NOT NULL,
    [business_date] date NOT NULL,
    [commodity] varchar(10) NOT NULL,
    [price_usd] decimal(19,6) NOT NULL,
    [price_unit] varchar(20) NOT NULL,
    [energy_factor] decimal(9,6) NOT NULL,
    CONSTRAINT [PK_ref_price] PRIMARY KEY ([batch_id], [business_date], [commodity])
);
GO

-- Source authority register (SNAPSHOT)
IF OBJECT_ID(N'ref.source_authority', N'U') IS NULL
CREATE TABLE [ref].[source_authority] (
    [batch_id] varchar(10) NOT NULL,
    [policy_version] varchar(20) NOT NULL,
    [domain] varchar(30) NOT NULL,
    [source_system] varchar(30) NOT NULL,
    [scope] varchar(10) NOT NULL,
    [priority] int NOT NULL,
    [eligible_status] varchar(20) NOT NULL,
    [valid_from] date NOT NULL,
    [valid_to] date NOT NULL,
    [owner_role] varchar(60) NOT NULL,
    CONSTRAINT [PK_ref_source_authority] PRIMARY KEY ([batch_id], [policy_version], [domain], [source_system], [scope])
);
GO

-- Algeria operator final production reports (EVENT)
IF OBJECT_ID(N'src_dz.production_report', N'U') IS NULL
CREATE TABLE [src_dz].[production_report] (
    [batch_id] varchar(10) NOT NULL,
    [change_id] varchar(64) NOT NULL,
    [change_seq] bigint NOT NULL,
    [observation_id] varchar(32) NOT NULL,
    [well_ref] varchar(30) NOT NULL,
    [report_date] date NOT NULL,
    [commodity] varchar(10) NOT NULL,
    [quantity] decimal(19,6) NULL,
    [unit] varchar(20) NOT NULL,
    [revision] int NOT NULL,
    [operation] char(1) NOT NULL,
    [report_status] varchar(20) NOT NULL,
    CONSTRAINT [PK_src_dz_production_report] PRIMARY KEY ([batch_id], [change_id])
);
GO

-- Malaysia operator final production reports (EVENT)
IF OBJECT_ID(N'src_my.production_report', N'U') IS NULL
CREATE TABLE [src_my].[production_report] (
    [batch_id] varchar(10) NOT NULL,
    [change_id] varchar(64) NOT NULL,
    [change_seq] bigint NOT NULL,
    [observation_id] varchar(32) NOT NULL,
    [well_ref] varchar(30) NOT NULL,
    [report_date] date NOT NULL,
    [commodity] varchar(10) NOT NULL,
    [quantity] decimal(19,6) NULL,
    [unit] varchar(20) NOT NULL,
    [revision] int NOT NULL,
    [operation] char(1) NOT NULL,
    [report_status] varchar(20) NOT NULL,
    CONSTRAINT [PK_src_my_production_report] PRIMARY KEY ([batch_id], [change_id])
);
GO

-- Malaysia daily operations provisional reports (EVENT)
IF OBJECT_ID(N'src_my.production_provisional', N'U') IS NULL
CREATE TABLE [src_my].[production_provisional] (
    [batch_id] varchar(10) NOT NULL,
    [change_id] varchar(64) NOT NULL,
    [change_seq] bigint NOT NULL,
    [observation_id] varchar(32) NOT NULL,
    [well_ref] varchar(30) NOT NULL,
    [report_date] date NOT NULL,
    [commodity] varchar(10) NOT NULL,
    [quantity] decimal(19,6) NULL,
    [unit] varchar(20) NOT NULL,
    [revision] int NOT NULL,
    [operation] char(1) NOT NULL,
    [report_status] varchar(20) NOT NULL,
    CONSTRAINT [PK_src_my_production_provisional] PRIMARY KEY ([batch_id], [change_id])
);
GO

-- Iraq daily volumes with local column names (EVENT)
IF OBJECT_ID(N'src_iq.daily_volumes', N'U') IS NULL
CREATE TABLE [src_iq].[daily_volumes] (
    [batch_id] varchar(10) NOT NULL,
    [chg_id] varchar(64) NOT NULL,
    [seq_no] bigint NOT NULL,
    [obs_key] varchar(32) NOT NULL,
    [well_code] varchar(30) NOT NULL,
    [obs_date] date NOT NULL,
    [product] varchar(5) NOT NULL,
    [qty] decimal(19,6) NULL,
    [qty_unit] varchar(20) NOT NULL,
    [rev_no] int NOT NULL,
    [op_code] char(1) NOT NULL,
    [approval_flag] char(1) NOT NULL,
    CONSTRAINT [PK_src_iq_daily_volumes] PRIMARY KEY ([batch_id], [chg_id])
);
GO

-- Maintenance downtime events (EVENT)
IF OBJECT_ID(N'src_my.downtime_event', N'U') IS NULL
CREATE TABLE [src_my].[downtime_event] (
    [batch_id] varchar(10) NOT NULL,
    [event_id] varchar(30) NOT NULL,
    [incident_id] varchar(30) NOT NULL,
    [equipment_id] varchar(20) NOT NULL,
    [start_utc] datetime2(0) NOT NULL,
    [end_utc] datetime2(0) NOT NULL,
    [reason] varchar(120) NOT NULL,
    [change_seq] bigint NOT NULL,
    CONSTRAINT [PK_src_my_downtime_event] PRIMARY KEY ([batch_id], [event_id])
);
GO

-- Approved production loss allocation (EVENT)
IF OBJECT_ID(N'src_my.loss_allocation', N'U') IS NULL
CREATE TABLE [src_my].[loss_allocation] (
    [batch_id] varchar(10) NOT NULL,
    [loss_id] varchar(40) NOT NULL,
    [event_id] varchar(30) NOT NULL,
    [well_ref] varchar(30) NOT NULL,
    [business_date] date NOT NULL,
    [lost_oil_bbl] decimal(19,6) NOT NULL,
    [lost_gas_mscf] decimal(19,6) NOT NULL,
    [allocation_status] varchar(20) NOT NULL,
    [change_seq] bigint NOT NULL,
    CONSTRAINT [PK_src_my_loss_allocation] PRIMARY KEY ([batch_id], [loss_id])
);
GO

-- Source batch manifest (CONTROL)
IF OBJECT_ID(N'ctl.source_batch', N'U') IS NULL
CREATE TABLE [ctl].[source_batch] (
    [batch_id] varchar(10) NOT NULL,
    [parent_batch_id] varchar(10) NULL,
    [dataset_version] varchar(30) NOT NULL,
    [description] varchar(200) NOT NULL,
    [period_start] date NOT NULL,
    [period_end] date NOT NULL,
    [state] varchar(10) NOT NULL,
    [content_sha256] char(64) NOT NULL,
    [sealed_at_utc] datetime2(0) NULL,
    CONSTRAINT [PK_ctl_source_batch] PRIMARY KEY ([batch_id])
);
GO

-- Expected row counts per batch and entity (CONTROL)
IF OBJECT_ID(N'ctl.batch_entity', N'U') IS NULL
CREATE TABLE [ctl].[batch_entity] (
    [batch_id] varchar(10) NOT NULL,
    [entity_name] varchar(80) NOT NULL,
    [row_count] bigint NOT NULL,
    [content_sha256] char(64) NOT NULL,
    CONSTRAINT [PK_ctl_batch_entity] PRIMARY KEY ([batch_id], [entity_name])
);
GO

-- Static Copy configuration read by the Fabric pipeline Lookup activity.
IF OBJECT_ID(N'ctl.entity_config', N'U') IS NULL
CREATE TABLE [ctl].[entity_config] (
    [entity_name] varchar(80) NOT NULL,
    [source_schema] varchar(30) NOT NULL,
    [source_table] varchar(80) NOT NULL,
    [entity_kind] varchar(10) NOT NULL,
    [enabled] bit NOT NULL,
    [ordinal] int NOT NULL,
    CONSTRAINT [PK_ctl_entity_config] PRIMARY KEY ([entity_name])
);
GO

IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__country')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__country', 'ref', 'country', 'SNAPSHOT', 1, 1);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__business_associate')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__business_associate', 'ref', 'business_associate', 'SNAPSHOT', 1, 2);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__field')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__field', 'ref', 'field', 'SNAPSHOT', 1, 3);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__facility')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__facility', 'ref', 'facility', 'SNAPSHOT', 1, 4);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__equipment')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__equipment', 'ref', 'equipment', 'SNAPSHOT', 1, 5);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__well')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__well', 'ref', 'well', 'SNAPSHOT', 1, 6);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__wellbore')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__wellbore', 'ref', 'wellbore', 'SNAPSHOT', 1, 7);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__well_completion')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__well_completion', 'ref', 'well_completion', 'SNAPSHOT', 1, 8);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__reporting_stream')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__reporting_stream', 'ref', 'reporting_stream', 'SNAPSHOT', 1, 9);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__well_alias')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__well_alias', 'ref', 'well_alias', 'SNAPSHOT', 1, 10);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__uom_conversion')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__uom_conversion', 'ref', 'uom_conversion', 'SNAPSHOT', 1, 11);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__working_interest')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__working_interest', 'ref', 'working_interest', 'SNAPSHOT', 1, 12);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__target_monthly')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__target_monthly', 'ref', 'target_monthly', 'SNAPSHOT', 1, 13);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__operating_cost')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__operating_cost', 'ref', 'operating_cost', 'SNAPSHOT', 1, 14);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__fx_rate')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__fx_rate', 'ref', 'fx_rate', 'SNAPSHOT', 1, 15);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__price')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__price', 'ref', 'price', 'SNAPSHOT', 1, 16);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ref__source_authority')
    INSERT INTO [ctl].[entity_config] VALUES ('ref__source_authority', 'ref', 'source_authority', 'SNAPSHOT', 1, 17);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'src_dz__production_report')
    INSERT INTO [ctl].[entity_config] VALUES ('src_dz__production_report', 'src_dz', 'production_report', 'EVENT', 1, 18);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'src_my__production_report')
    INSERT INTO [ctl].[entity_config] VALUES ('src_my__production_report', 'src_my', 'production_report', 'EVENT', 1, 19);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'src_my__production_provisional')
    INSERT INTO [ctl].[entity_config] VALUES ('src_my__production_provisional', 'src_my', 'production_provisional', 'EVENT', 1, 20);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'src_iq__daily_volumes')
    INSERT INTO [ctl].[entity_config] VALUES ('src_iq__daily_volumes', 'src_iq', 'daily_volumes', 'EVENT', 1, 21);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'src_my__downtime_event')
    INSERT INTO [ctl].[entity_config] VALUES ('src_my__downtime_event', 'src_my', 'downtime_event', 'EVENT', 1, 22);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'src_my__loss_allocation')
    INSERT INTO [ctl].[entity_config] VALUES ('src_my__loss_allocation', 'src_my', 'loss_allocation', 'EVENT', 1, 23);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ctl__source_batch')
    INSERT INTO [ctl].[entity_config] VALUES ('ctl__source_batch', 'ctl', 'source_batch', 'CONTROL', 1, 24);
IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = 'ctl__batch_entity')
    INSERT INTO [ctl].[entity_config] VALUES ('ctl__batch_entity', 'ctl', 'batch_entity', 'CONTROL', 1, 25);
GO

SELECT COUNT(*) AS configured_entities FROM [ctl].[entity_config] WHERE [enabled] = 1;
GO
