"""Render Azure SQL DDL and seed scripts from the source contract."""

from __future__ import annotations

from .contracts import COPY_ENTITIES, TABLES

HEADER = (
    "-- Generated by `python -m workshop render-sql` from workshop/contracts.py.\n"
    "-- Do not edit by hand. Target: Azure SQL Database (workshop source systems).\n"
    "-- Safe to re-run: objects are created only when missing.\n"
)


def _column(column) -> str:
    return f"    [{column.name}] {column.sql_type} {'NULL' if column.nullable else 'NOT NULL'}"


def render_source_schema() -> str:
    parts = [HEADER, "SET NOCOUNT ON;", "GO", ""]
    for schema in sorted({table.schema for table in TABLES}):
        parts += [f"IF SCHEMA_ID(N'{schema}') IS NULL EXEC(N'CREATE SCHEMA [{schema}]');", "GO"]
    parts.append("")
    for table in TABLES:
        constraint = f"PK_{table.schema}_{table.name}"
        key = ", ".join(f"[{name}]" for name in table.key)
        columns = ",\n".join(_column(c) for c in table.columns)
        parts += [
            f"-- {table.description} ({table.kind})",
            f"IF OBJECT_ID(N'{table.full_name}', N'U') IS NULL",
            f"CREATE TABLE [{table.schema}].[{table.name}] (\n{columns},\n"
            f"    CONSTRAINT [{constraint}] PRIMARY KEY ([{table.key[0]}]{', ' if len(table.key) > 1 else ''}"
            f"{', '.join(f'[{k}]' for k in table.key[1:])})\n);",
            "GO", "",
        ]
        assert key  # documents that every table has a key
    parts += [
        "-- Static Copy configuration read by the Fabric pipeline Lookup activity.",
        "IF OBJECT_ID(N'ctl.entity_config', N'U') IS NULL",
        "CREATE TABLE [ctl].[entity_config] (\n"
        "    [entity_name] varchar(80) NOT NULL,\n    [source_schema] varchar(30) NOT NULL,\n"
        "    [source_table] varchar(80) NOT NULL,\n    [entity_kind] varchar(10) NOT NULL,\n"
        "    [enabled] bit NOT NULL,\n    [ordinal] int NOT NULL,\n"
        "    CONSTRAINT [PK_ctl_entity_config] PRIMARY KEY ([entity_name])\n);",
        "GO", "",
    ]
    for ordinal, table in enumerate(COPY_ENTITIES, 1):
        parts.append(
            f"IF NOT EXISTS (SELECT 1 FROM [ctl].[entity_config] WHERE [entity_name] = '{table.entity}')\n"
            f"    INSERT INTO [ctl].[entity_config] VALUES ('{table.entity}', '{table.schema}', "
            f"'{table.name}', '{table.kind}', 1, {ordinal});")
    parts += ["GO", "", "SELECT COUNT(*) AS configured_entities FROM [ctl].[entity_config] WHERE [enabled] = 1;", "GO", ""]
    return "\n".join(parts)
