-- Generated by `python -m workshop render-warehouse` from workshop/warehouse.py. Do not edit by hand.
-- Target: Fabric Warehouse wh_zava_gold (same workspace as lh_zava_core). Safe to re-run.

IF SCHEMA_ID(N'stg') IS NULL EXEC(N'CREATE SCHEMA [stg]');
GO
IF SCHEMA_ID(N'gold') IS NULL EXEC(N'CREATE SCHEMA [gold]');
GO
IF SCHEMA_ID(N'ops') IS NULL EXEC(N'CREATE SCHEMA [ops]');
GO

-- stg: kandidat publikasi (beberapa PublicationId); gold: satu publikasi yang disetujui
IF OBJECT_ID(N'stg.dim_date', N'U') IS NULL
CREATE TABLE [stg].[dim_date] (
    [DateKey] int NOT NULL,
    [Date] date NOT NULL,
    [Year] int NOT NULL,
    [MonthNumber] int NOT NULL,
    [MonthName] varchar(3) NOT NULL,
    [YearMonth] varchar(7) NOT NULL,
    [MonthStart] date NOT NULL,
    [DayOfMonth] int NOT NULL,
    [DaysInMonth] int NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.dim_date', N'U') IS NULL
CREATE TABLE [gold].[dim_date] (
    [DateKey] int NOT NULL,
    [Date] date NOT NULL,
    [Year] int NOT NULL,
    [MonthNumber] int NOT NULL,
    [MonthName] varchar(3) NOT NULL,
    [YearMonth] varchar(7) NOT NULL,
    [MonthStart] date NOT NULL,
    [DayOfMonth] int NOT NULL,
    [DaysInMonth] int NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.dim_asset', N'U') IS NULL
CREATE TABLE [stg].[dim_asset] (
    [AssetKey] bigint NOT NULL,
    [AssetId] varchar(10) NOT NULL,
    [AssetName] varchar(100) NOT NULL,
    [CountryCode] varchar(2) NOT NULL,
    [CountryName] varchar(100) NOT NULL,
    [FacilityId] varchar(20) NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.dim_asset', N'U') IS NULL
CREATE TABLE [gold].[dim_asset] (
    [AssetKey] bigint NOT NULL,
    [AssetId] varchar(10) NOT NULL,
    [AssetName] varchar(100) NOT NULL,
    [CountryCode] varchar(2) NOT NULL,
    [CountryName] varchar(100) NOT NULL,
    [FacilityId] varchar(20) NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.dim_well', N'U') IS NULL
CREATE TABLE [stg].[dim_well] (
    [WellKey] bigint NOT NULL,
    [WellId] varchar(20) NOT NULL,
    [WellName] varchar(100) NOT NULL,
    [AssetKey] bigint NOT NULL,
    [AssetId] varchar(10) NOT NULL,
    [CountryCode] varchar(2) NOT NULL,
    [StreamId] varchar(30) NOT NULL,
    [WellboreCount] int NOT NULL,
    [CompletionCount] int NOT NULL,
    [AliasList] varchar(1000) NULL,
    [WellStatus] varchar(20) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.dim_well', N'U') IS NULL
CREATE TABLE [gold].[dim_well] (
    [WellKey] bigint NOT NULL,
    [WellId] varchar(20) NOT NULL,
    [WellName] varchar(100) NOT NULL,
    [AssetKey] bigint NOT NULL,
    [AssetId] varchar(10) NOT NULL,
    [CountryCode] varchar(2) NOT NULL,
    [StreamId] varchar(30) NOT NULL,
    [WellboreCount] int NOT NULL,
    [CompletionCount] int NOT NULL,
    [AliasList] varchar(1000) NULL,
    [WellStatus] varchar(20) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.dim_equipment', N'U') IS NULL
CREATE TABLE [stg].[dim_equipment] (
    [EquipmentKey] bigint NOT NULL,
    [EquipmentId] varchar(20) NOT NULL,
    [EquipmentName] varchar(100) NOT NULL,
    [EquipmentType] varchar(40) NOT NULL,
    [FacilityId] varchar(20) NOT NULL,
    [AssetKey] bigint NOT NULL,
    [AssetId] varchar(10) NOT NULL,
    [CountryCode] varchar(2) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.dim_equipment', N'U') IS NULL
CREATE TABLE [gold].[dim_equipment] (
    [EquipmentKey] bigint NOT NULL,
    [EquipmentId] varchar(20) NOT NULL,
    [EquipmentName] varchar(100) NOT NULL,
    [EquipmentType] varchar(40) NOT NULL,
    [FacilityId] varchar(20) NOT NULL,
    [AssetKey] bigint NOT NULL,
    [AssetId] varchar(10) NOT NULL,
    [CountryCode] varchar(2) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.dim_incident', N'U') IS NULL
CREATE TABLE [stg].[dim_incident] (
    [IncidentKey] bigint NOT NULL,
    [IncidentId] varchar(30) NOT NULL,
    [IncidentCategory] varchar(30) NOT NULL,
    [EventCount] int NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.dim_incident', N'U') IS NULL
CREATE TABLE [gold].[dim_incident] (
    [IncidentKey] bigint NOT NULL,
    [IncidentId] varchar(30) NOT NULL,
    [IncidentCategory] varchar(30) NOT NULL,
    [EventCount] int NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.dim_scenario', N'U') IS NULL
CREATE TABLE [stg].[dim_scenario] (
    [ScenarioKey] bigint NOT NULL,
    [ScenarioId] varchar(20) NOT NULL,
    [ScenarioName] varchar(100) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.dim_scenario', N'U') IS NULL
CREATE TABLE [gold].[dim_scenario] (
    [ScenarioKey] bigint NOT NULL,
    [ScenarioId] varchar(20) NOT NULL,
    [ScenarioName] varchar(100) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.dim_cost_category', N'U') IS NULL
CREATE TABLE [stg].[dim_cost_category] (
    [CostCategoryKey] bigint NOT NULL,
    [CostCategory] varchar(30) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.dim_cost_category', N'U') IS NULL
CREATE TABLE [gold].[dim_cost_category] (
    [CostCategoryKey] bigint NOT NULL,
    [CostCategory] varchar(30) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.fact_production_daily', N'U') IS NULL
CREATE TABLE [stg].[fact_production_daily] (
    [DateKey] int NOT NULL,
    [WellKey] bigint NOT NULL,
    [AssetKey] bigint NOT NULL,
    [StreamId] varchar(30) NOT NULL,
    [OilBbl] decimal(19,6) NULL,
    [GasMscf] decimal(19,6) NULL,
    [WaterBbl] decimal(19,6) NULL,
    [GrossBoe] decimal(19,6) NULL,
    [WiShare] decimal(9,6) NULL,
    [NetWiBoe] decimal(19,6) NULL,
    [ObservationCount] int NOT NULL,
    [ExpectedObservationCount] int NOT NULL,
    [IsComplete] int NOT NULL,
    [RetractedCount] int NOT NULL,
    [SelectedSources] varchar(200) NULL,
    [MaxRevision] int NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.fact_production_daily', N'U') IS NULL
CREATE TABLE [gold].[fact_production_daily] (
    [DateKey] int NOT NULL,
    [WellKey] bigint NOT NULL,
    [AssetKey] bigint NOT NULL,
    [StreamId] varchar(30) NOT NULL,
    [OilBbl] decimal(19,6) NULL,
    [GasMscf] decimal(19,6) NULL,
    [WaterBbl] decimal(19,6) NULL,
    [GrossBoe] decimal(19,6) NULL,
    [WiShare] decimal(9,6) NULL,
    [NetWiBoe] decimal(19,6) NULL,
    [ObservationCount] int NOT NULL,
    [ExpectedObservationCount] int NOT NULL,
    [IsComplete] int NOT NULL,
    [RetractedCount] int NOT NULL,
    [SelectedSources] varchar(200) NULL,
    [MaxRevision] int NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.fact_target_daily', N'U') IS NULL
CREATE TABLE [stg].[fact_target_daily] (
    [DateKey] int NOT NULL,
    [AssetKey] bigint NOT NULL,
    [ScenarioKey] bigint NOT NULL,
    [TargetOilBbl] decimal(19,6) NULL,
    [TargetGasMscf] decimal(19,6) NULL,
    [TargetBoe] decimal(19,6) NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.fact_target_daily', N'U') IS NULL
CREATE TABLE [gold].[fact_target_daily] (
    [DateKey] int NOT NULL,
    [AssetKey] bigint NOT NULL,
    [ScenarioKey] bigint NOT NULL,
    [TargetOilBbl] decimal(19,6) NULL,
    [TargetGasMscf] decimal(19,6) NULL,
    [TargetBoe] decimal(19,6) NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.fact_operating_cost_monthly', N'U') IS NULL
CREATE TABLE [stg].[fact_operating_cost_monthly] (
    [MonthDateKey] int NOT NULL,
    [AssetKey] bigint NOT NULL,
    [CostCategoryKey] bigint NOT NULL,
    [CurrencyCode] varchar(3) NOT NULL,
    [AmountLocal] decimal(19,4) NOT NULL,
    [UsdPerUnit] decimal(18,9) NOT NULL,
    [AmountUsd] decimal(19,4) NOT NULL,
    [ClosingStatus] varchar(20) NOT NULL,
    [CostId] varchar(30) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.fact_operating_cost_monthly', N'U') IS NULL
CREATE TABLE [gold].[fact_operating_cost_monthly] (
    [MonthDateKey] int NOT NULL,
    [AssetKey] bigint NOT NULL,
    [CostCategoryKey] bigint NOT NULL,
    [CurrencyCode] varchar(3) NOT NULL,
    [AmountLocal] decimal(19,4) NOT NULL,
    [UsdPerUnit] decimal(18,9) NOT NULL,
    [AmountUsd] decimal(19,4) NOT NULL,
    [ClosingStatus] varchar(20) NOT NULL,
    [CostId] varchar(30) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.fact_downtime_event', N'U') IS NULL
CREATE TABLE [stg].[fact_downtime_event] (
    [EventId] varchar(30) NOT NULL,
    [IncidentKey] bigint NOT NULL,
    [EquipmentKey] bigint NOT NULL,
    [AssetKey] bigint NOT NULL,
    [StartDateKey] int NOT NULL,
    [StartUtc] datetime2(6) NOT NULL,
    [EndUtc] datetime2(6) NOT NULL,
    [DurationHours] decimal(9,3) NOT NULL,
    [Reason] varchar(120) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.fact_downtime_event', N'U') IS NULL
CREATE TABLE [gold].[fact_downtime_event] (
    [EventId] varchar(30) NOT NULL,
    [IncidentKey] bigint NOT NULL,
    [EquipmentKey] bigint NOT NULL,
    [AssetKey] bigint NOT NULL,
    [StartDateKey] int NOT NULL,
    [StartUtc] datetime2(6) NOT NULL,
    [EndUtc] datetime2(6) NOT NULL,
    [DurationHours] decimal(9,3) NOT NULL,
    [Reason] varchar(120) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.fact_loss_allocation', N'U') IS NULL
CREATE TABLE [stg].[fact_loss_allocation] (
    [LossId] varchar(40) NOT NULL,
    [DateKey] int NOT NULL,
    [WellKey] bigint NOT NULL,
    [AssetKey] bigint NOT NULL,
    [IncidentKey] bigint NOT NULL,
    [EquipmentKey] bigint NOT NULL,
    [EventId] varchar(30) NOT NULL,
    [LostOilBbl] decimal(19,6) NOT NULL,
    [LostGasMscf] decimal(19,6) NOT NULL,
    [LostBoeGross] decimal(19,6) NOT NULL,
    [WiShare] decimal(9,6) NOT NULL,
    [LostBoeNetWi] decimal(19,6) NOT NULL,
    [ValueUsdGross] decimal(19,4) NOT NULL,
    [ValueUsdNetWi] decimal(19,4) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.fact_loss_allocation', N'U') IS NULL
CREATE TABLE [gold].[fact_loss_allocation] (
    [LossId] varchar(40) NOT NULL,
    [DateKey] int NOT NULL,
    [WellKey] bigint NOT NULL,
    [AssetKey] bigint NOT NULL,
    [IncidentKey] bigint NOT NULL,
    [EquipmentKey] bigint NOT NULL,
    [EventId] varchar(30) NOT NULL,
    [LostOilBbl] decimal(19,6) NOT NULL,
    [LostGasMscf] decimal(19,6) NOT NULL,
    [LostBoeGross] decimal(19,6) NOT NULL,
    [WiShare] decimal(9,6) NOT NULL,
    [LostBoeNetWi] decimal(19,6) NOT NULL,
    [ValueUsdGross] decimal(19,4) NOT NULL,
    [ValueUsdNetWi] decimal(19,4) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.master_wellbore', N'U') IS NULL
CREATE TABLE [stg].[master_wellbore] (
    [WellboreId] varchar(30) NOT NULL,
    [WellId] varchar(20) NOT NULL,
    [WellboreName] varchar(100) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.master_wellbore', N'U') IS NULL
CREATE TABLE [gold].[master_wellbore] (
    [WellboreId] varchar(30) NOT NULL,
    [WellId] varchar(20) NOT NULL,
    [WellboreName] varchar(100) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.master_completion', N'U') IS NULL
CREATE TABLE [stg].[master_completion] (
    [CompletionId] varchar(40) NOT NULL,
    [WellboreId] varchar(30) NOT NULL,
    [StreamId] varchar(30) NOT NULL,
    [CompletionName] varchar(100) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.master_completion', N'U') IS NULL
CREATE TABLE [gold].[master_completion] (
    [CompletionId] varchar(40) NOT NULL,
    [WellboreId] varchar(30) NOT NULL,
    [StreamId] varchar(30) NOT NULL,
    [CompletionName] varchar(100) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'stg.source_decision', N'U') IS NULL
CREATE TABLE [stg].[source_decision] (
    [DecisionId] varchar(64) NOT NULL,
    [CanonicalKey] varchar(80) NOT NULL,
    [StreamId] varchar(30) NOT NULL,
    [WellId] varchar(20) NOT NULL,
    [BusinessDate] date NOT NULL,
    [Commodity] varchar(10) NOT NULL,
    [CandidateCount] int NOT NULL,
    [DecisionStatus] varchar(30) NOT NULL,
    [SelectedSourceSystem] varchar(30) NULL,
    [SelectedObservationId] varchar(32) NULL,
    [SelectedRevision] int NULL,
    [SelectedValueStd] decimal(19,6) NULL,
    [Reason] varchar(400) NULL,
    [CandidatesJson] varchar(4000) NULL,
    [AuthorityPolicyVersion] varchar(20) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

IF OBJECT_ID(N'gold.source_decision', N'U') IS NULL
CREATE TABLE [gold].[source_decision] (
    [DecisionId] varchar(64) NOT NULL,
    [CanonicalKey] varchar(80) NOT NULL,
    [StreamId] varchar(30) NOT NULL,
    [WellId] varchar(20) NOT NULL,
    [BusinessDate] date NOT NULL,
    [Commodity] varchar(10) NOT NULL,
    [CandidateCount] int NOT NULL,
    [DecisionStatus] varchar(30) NOT NULL,
    [SelectedSourceSystem] varchar(30) NULL,
    [SelectedObservationId] varchar(32) NULL,
    [SelectedRevision] int NULL,
    [SelectedValueStd] decimal(19,6) NULL,
    [Reason] varchar(400) NULL,
    [CandidatesJson] varchar(4000) NULL,
    [AuthorityPolicyVersion] varchar(20) NOT NULL,
    [PublicationId] varchar(30) NOT NULL
);
GO

-- ops: manifest publikasi, approval, bukti kualitas, dan status konsumen
IF OBJECT_ID(N'ops.publication', N'U') IS NULL
CREATE TABLE [ops].[publication] (
    [PublicationId] varchar(30) NOT NULL,
    [BatchId] varchar(10) NOT NULL,
    [ParentBatchId] varchar(10) NULL,
    [DatasetVersion] varchar(30) NULL,
    [AuthorityPolicyVersion] varchar(20) NULL,
    [MappingVersion] varchar(30) NULL,
    [KpiContractVersion] varchar(20) NULL,
    [UomFactorVersion] varchar(20) NULL,
    [PeriodStart] date NULL,
    [PeriodEnd] date NULL,
    [ControlTotalsJson] varchar(4000) NULL,
    [BlockerCount] int NOT NULL,
    [WarningCount] int NOT NULL,
    [InfoCount] int NOT NULL,
    [Status] varchar(30) NOT NULL,
    [StagedAtUtc] datetime2(6) NULL,
    [DecidedBy] varchar(256) NULL,
    [DecidedAtUtc] datetime2(6) NULL,
    [DecisionComment] varchar(1000) NULL,
    [PublishedAtUtc] datetime2(6) NULL,
    [SupersededBy] varchar(30) NULL,
    [RunId] varchar(100) NULL
);
GO

IF OBJECT_ID(N'ops.publication_event', N'U') IS NULL
CREATE TABLE [ops].[publication_event] (
    [PublicationId] varchar(30) NOT NULL,
    [EventType] varchar(40) NOT NULL,
    [Actor] varchar(256) NOT NULL,
    [Detail] varchar(4000) NULL,
    [EventAtUtc] datetime2(6) NOT NULL
);
GO

IF OBJECT_ID(N'ops.authorized_approver', N'U') IS NULL
CREATE TABLE [ops].[authorized_approver] (
    [ApproverUpn] varchar(256) NOT NULL,
    [ApproverRole] varchar(100) NOT NULL,
    [DataDomain] varchar(30) NOT NULL,
    [IsActive] bit NOT NULL
);
GO

IF OBJECT_ID(N'ops.kpi_contract', N'U') IS NULL
CREATE TABLE [ops].[kpi_contract] (
    [KpiId] varchar(20) NOT NULL,
    [KpiName] varchar(100) NOT NULL,
    [Definition] varchar(1000) NOT NULL,
    [Unit] varchar(20) NOT NULL,
    [Grain] varchar(100) NOT NULL,
    [DataOwner] varchar(100) NOT NULL,
    [SourceColumn] varchar(200) NOT NULL,
    [ContractVersion] varchar(20) NOT NULL
);
GO

IF OBJECT_ID(N'ops.quality_evidence', N'U') IS NULL
CREATE TABLE [ops].[quality_evidence] (
    [BatchId] varchar(10) NOT NULL,
    [Stage] varchar(30) NOT NULL,
    [Status] varchar(40) NOT NULL,
    [PublicationId] varchar(30) NULL,
    [BlockerCount] int NOT NULL,
    [WarningCount] int NOT NULL,
    [InfoCount] int NOT NULL,
    [Message] varchar(4000) NULL,
    [RunId] varchar(100) NULL,
    [UpdatedAtUtc] datetime2(6) NULL,
    [SyncedAtUtc] datetime2(6) NOT NULL
);
GO

IF OBJECT_ID(N'ops.dq_issue_summary', N'U') IS NULL
CREATE TABLE [ops].[dq_issue_summary] (
    [BatchId] varchar(10) NOT NULL,
    [Stage] varchar(30) NOT NULL,
    [RuleId] varchar(10) NOT NULL,
    [Severity] varchar(10) NOT NULL,
    [IssueCount] int NOT NULL,
    [SyncedAtUtc] datetime2(6) NOT NULL
);
GO

IF OBJECT_ID(N'ops.consumer_status', N'U') IS NULL
CREATE TABLE [ops].[consumer_status] (
    [PublicationId] varchar(30) NOT NULL,
    [Consumer] varchar(60) NOT NULL,
    [Status] varchar(30) NOT NULL,
    [Detail] varchar(1000) NULL,
    [UpdatedAtUtc] datetime2(6) NOT NULL
);
GO

-- Constraint informatif (NOT ENFORCED) membantu optimizer dan relasi semantic model
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'PK_gold_dim_date')
    ALTER TABLE [gold].[dim_date] ADD CONSTRAINT [PK_gold_dim_date] PRIMARY KEY NONCLUSTERED ([DateKey]) NOT ENFORCED;
GO
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'PK_gold_dim_asset')
    ALTER TABLE [gold].[dim_asset] ADD CONSTRAINT [PK_gold_dim_asset] PRIMARY KEY NONCLUSTERED ([AssetKey]) NOT ENFORCED;
GO
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'PK_gold_dim_well')
    ALTER TABLE [gold].[dim_well] ADD CONSTRAINT [PK_gold_dim_well] PRIMARY KEY NONCLUSTERED ([WellKey]) NOT ENFORCED;
GO
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'PK_gold_dim_equipment')
    ALTER TABLE [gold].[dim_equipment] ADD CONSTRAINT [PK_gold_dim_equipment] PRIMARY KEY NONCLUSTERED ([EquipmentKey]) NOT ENFORCED;
GO
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'PK_gold_dim_incident')
    ALTER TABLE [gold].[dim_incident] ADD CONSTRAINT [PK_gold_dim_incident] PRIMARY KEY NONCLUSTERED ([IncidentKey]) NOT ENFORCED;
GO
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'PK_gold_dim_scenario')
    ALTER TABLE [gold].[dim_scenario] ADD CONSTRAINT [PK_gold_dim_scenario] PRIMARY KEY NONCLUSTERED ([ScenarioKey]) NOT ENFORCED;
GO
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'PK_gold_dim_cost_category')
    ALTER TABLE [gold].[dim_cost_category] ADD CONSTRAINT [PK_gold_dim_cost_category] PRIMARY KEY NONCLUSTERED ([CostCategoryKey]) NOT ENFORCED;
GO
IF NOT EXISTS (SELECT 1 FROM sys.key_constraints WHERE name = N'PK_ops_publication')
    ALTER TABLE [ops].[publication] ADD CONSTRAINT [PK_ops_publication] PRIMARY KEY NONCLUSTERED ([PublicationId]) NOT ENFORCED;
GO
CREATE OR ALTER VIEW ops.vw_current_publication AS
SELECT p.PublicationId, p.BatchId, p.DatasetVersion, p.AuthorityPolicyVersion, p.MappingVersion,
       p.KpiContractVersion, p.PeriodStart, p.PeriodEnd, p.DecidedBy AS ApprovedBy, p.DecidedAtUtc AS ApprovedAtUtc,
       p.PublishedAtUtc, p.ControlTotalsJson
FROM ops.publication AS p
WHERE p.Status = 'PUBLISHED';
GO

CREATE OR ALTER VIEW ops.vw_publication_history AS
SELECT PublicationId, BatchId, Status, BlockerCount, WarningCount, InfoCount, StagedAtUtc, DecidedBy, DecidedAtUtc,
       DecisionComment, PublishedAtUtc, SupersededBy, AuthorityPolicyVersion, MappingVersion
FROM ops.publication;
GO

