-- Generated by `python -m workshop render-warehouse` from workshop/warehouse.py. Do not edit by hand.
-- Prosedur siklus publikasi SSOT: stage -> approve -> publish, plus bukti kualitas dan status konsumen.

CREATE OR ALTER PROCEDURE ops.usp_stage_candidate
    @PublicationId varchar(30),
    @RunId varchar(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now datetime2(6) = SYSUTCDATETIME();

    IF EXISTS (SELECT 1 FROM ops.publication WHERE PublicationId = @PublicationId AND Status = 'PUBLISHED')
    BEGIN
        SELECT @PublicationId AS PublicationId, 'ALREADY_PUBLISHED' AS Result;
        RETURN;
    END;
    IF (SELECT COUNT(*) FROM lh_piep_core.serve.publication_candidate WHERE PublicationId = @PublicationId) <> 1
        THROW 50010, 'Publication candidate not found in lh_piep_core.serve.publication_candidate. Run nb_05 first or wait for SQL analytics endpoint sync.', 1;

    -- Tunggu sinkronisasi metadata SQL analytics endpoint: row count harus sama dengan manifest nb_05
    DECLARE @expectedTables int, @mismatches int;
    SELECT @expectedTables = COUNT(*) FROM lh_piep_core.serve.publication_row_count WHERE PublicationId = @PublicationId;
    SELECT @mismatches = COUNT(*)
    FROM (
        SELECT 'dim_date' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.dim_date WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'dim_asset' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.dim_asset WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'dim_well' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.dim_well WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'dim_equipment' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.dim_equipment WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'dim_incident' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.dim_incident WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'dim_scenario' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.dim_scenario WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'dim_cost_category' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.dim_cost_category WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'fact_production_daily' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.fact_production_daily WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'fact_target_daily' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.fact_target_daily WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'fact_operating_cost_monthly' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.fact_operating_cost_monthly WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'fact_downtime_event' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.fact_downtime_event WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'fact_loss_allocation' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.fact_loss_allocation WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'master_wellbore' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.master_wellbore WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'master_completion' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.master_completion WHERE PublicationId = @PublicationId
        UNION ALL SELECT 'source_decision' AS TableName, COUNT_BIG(*) AS ActualRows FROM lh_piep_core.serve.source_decision WHERE PublicationId = @PublicationId
    ) AS a
    JOIN lh_piep_core.serve.publication_row_count AS e
      ON e.TableName = a.TableName AND e.PublicationId = @PublicationId
    WHERE e.ExpectedRows <> a.ActualRows;
    IF @expectedTables <> 15 OR @mismatches <> 0
        THROW 50011, 'Lakehouse serve tables are not yet visible with the expected row counts (SQL analytics endpoint sync). Retry later.', 1;

    BEGIN TRANSACTION;
    BEGIN TRY
        DELETE FROM stg.dim_date WHERE PublicationId = @PublicationId;
        INSERT INTO stg.dim_date ([DateKey], [Date], [Year], [MonthNumber], [MonthName], [YearMonth], [MonthStart], [DayOfMonth], [DaysInMonth], [PublicationId])
        SELECT [DateKey], [Date], [Year], [MonthNumber], [MonthName], [YearMonth], [MonthStart], [DayOfMonth], [DaysInMonth], [PublicationId] FROM lh_piep_core.serve.dim_date WHERE PublicationId = @PublicationId;
        DELETE FROM stg.dim_asset WHERE PublicationId = @PublicationId;
        INSERT INTO stg.dim_asset ([AssetKey], [AssetId], [AssetName], [CountryCode], [CountryName], [FacilityId], [PublicationId])
        SELECT [AssetKey], [AssetId], [AssetName], [CountryCode], [CountryName], [FacilityId], [PublicationId] FROM lh_piep_core.serve.dim_asset WHERE PublicationId = @PublicationId;
        DELETE FROM stg.dim_well WHERE PublicationId = @PublicationId;
        INSERT INTO stg.dim_well ([WellKey], [WellId], [WellName], [AssetKey], [AssetId], [CountryCode], [StreamId], [WellboreCount], [CompletionCount], [AliasList], [WellStatus], [PublicationId])
        SELECT [WellKey], [WellId], [WellName], [AssetKey], [AssetId], [CountryCode], [StreamId], [WellboreCount], [CompletionCount], [AliasList], [WellStatus], [PublicationId] FROM lh_piep_core.serve.dim_well WHERE PublicationId = @PublicationId;
        DELETE FROM stg.dim_equipment WHERE PublicationId = @PublicationId;
        INSERT INTO stg.dim_equipment ([EquipmentKey], [EquipmentId], [EquipmentName], [EquipmentType], [FacilityId], [AssetKey], [AssetId], [CountryCode], [PublicationId])
        SELECT [EquipmentKey], [EquipmentId], [EquipmentName], [EquipmentType], [FacilityId], [AssetKey], [AssetId], [CountryCode], [PublicationId] FROM lh_piep_core.serve.dim_equipment WHERE PublicationId = @PublicationId;
        DELETE FROM stg.dim_incident WHERE PublicationId = @PublicationId;
        INSERT INTO stg.dim_incident ([IncidentKey], [IncidentId], [IncidentCategory], [EventCount], [PublicationId])
        SELECT [IncidentKey], [IncidentId], [IncidentCategory], [EventCount], [PublicationId] FROM lh_piep_core.serve.dim_incident WHERE PublicationId = @PublicationId;
        DELETE FROM stg.dim_scenario WHERE PublicationId = @PublicationId;
        INSERT INTO stg.dim_scenario ([ScenarioKey], [ScenarioId], [ScenarioName], [PublicationId])
        SELECT [ScenarioKey], [ScenarioId], [ScenarioName], [PublicationId] FROM lh_piep_core.serve.dim_scenario WHERE PublicationId = @PublicationId;
        DELETE FROM stg.dim_cost_category WHERE PublicationId = @PublicationId;
        INSERT INTO stg.dim_cost_category ([CostCategoryKey], [CostCategory], [PublicationId])
        SELECT [CostCategoryKey], [CostCategory], [PublicationId] FROM lh_piep_core.serve.dim_cost_category WHERE PublicationId = @PublicationId;
        DELETE FROM stg.fact_production_daily WHERE PublicationId = @PublicationId;
        INSERT INTO stg.fact_production_daily ([DateKey], [WellKey], [AssetKey], [StreamId], [OilBbl], [GasMscf], [WaterBbl], [GrossBoe], [WiShare], [NetWiBoe], [ObservationCount], [ExpectedObservationCount], [IsComplete], [RetractedCount], [SelectedSources], [MaxRevision], [PublicationId])
        SELECT [DateKey], [WellKey], [AssetKey], [StreamId], [OilBbl], [GasMscf], [WaterBbl], [GrossBoe], [WiShare], [NetWiBoe], [ObservationCount], [ExpectedObservationCount], [IsComplete], [RetractedCount], [SelectedSources], [MaxRevision], [PublicationId] FROM lh_piep_core.serve.fact_production_daily WHERE PublicationId = @PublicationId;
        DELETE FROM stg.fact_target_daily WHERE PublicationId = @PublicationId;
        INSERT INTO stg.fact_target_daily ([DateKey], [AssetKey], [ScenarioKey], [TargetOilBbl], [TargetGasMscf], [TargetBoe], [PublicationId])
        SELECT [DateKey], [AssetKey], [ScenarioKey], [TargetOilBbl], [TargetGasMscf], [TargetBoe], [PublicationId] FROM lh_piep_core.serve.fact_target_daily WHERE PublicationId = @PublicationId;
        DELETE FROM stg.fact_operating_cost_monthly WHERE PublicationId = @PublicationId;
        INSERT INTO stg.fact_operating_cost_monthly ([MonthDateKey], [AssetKey], [CostCategoryKey], [CurrencyCode], [AmountLocal], [UsdPerUnit], [AmountUsd], [ClosingStatus], [CostId], [PublicationId])
        SELECT [MonthDateKey], [AssetKey], [CostCategoryKey], [CurrencyCode], [AmountLocal], [UsdPerUnit], [AmountUsd], [ClosingStatus], [CostId], [PublicationId] FROM lh_piep_core.serve.fact_operating_cost_monthly WHERE PublicationId = @PublicationId;
        DELETE FROM stg.fact_downtime_event WHERE PublicationId = @PublicationId;
        INSERT INTO stg.fact_downtime_event ([EventId], [IncidentKey], [EquipmentKey], [AssetKey], [StartDateKey], [StartUtc], [EndUtc], [DurationHours], [Reason], [PublicationId])
        SELECT [EventId], [IncidentKey], [EquipmentKey], [AssetKey], [StartDateKey], [StartUtc], [EndUtc], [DurationHours], [Reason], [PublicationId] FROM lh_piep_core.serve.fact_downtime_event WHERE PublicationId = @PublicationId;
        DELETE FROM stg.fact_loss_allocation WHERE PublicationId = @PublicationId;
        INSERT INTO stg.fact_loss_allocation ([LossId], [DateKey], [WellKey], [AssetKey], [IncidentKey], [EquipmentKey], [EventId], [LostOilBbl], [LostGasMscf], [LostBoeGross], [WiShare], [LostBoeNetWi], [ValueUsdGross], [ValueUsdNetWi], [PublicationId])
        SELECT [LossId], [DateKey], [WellKey], [AssetKey], [IncidentKey], [EquipmentKey], [EventId], [LostOilBbl], [LostGasMscf], [LostBoeGross], [WiShare], [LostBoeNetWi], [ValueUsdGross], [ValueUsdNetWi], [PublicationId] FROM lh_piep_core.serve.fact_loss_allocation WHERE PublicationId = @PublicationId;
        DELETE FROM stg.master_wellbore WHERE PublicationId = @PublicationId;
        INSERT INTO stg.master_wellbore ([WellboreId], [WellId], [WellboreName], [PublicationId])
        SELECT [WellboreId], [WellId], [WellboreName], [PublicationId] FROM lh_piep_core.serve.master_wellbore WHERE PublicationId = @PublicationId;
        DELETE FROM stg.master_completion WHERE PublicationId = @PublicationId;
        INSERT INTO stg.master_completion ([CompletionId], [WellboreId], [StreamId], [CompletionName], [PublicationId])
        SELECT [CompletionId], [WellboreId], [StreamId], [CompletionName], [PublicationId] FROM lh_piep_core.serve.master_completion WHERE PublicationId = @PublicationId;
        DELETE FROM stg.source_decision WHERE PublicationId = @PublicationId;
        INSERT INTO stg.source_decision ([DecisionId], [CanonicalKey], [StreamId], [WellId], [BusinessDate], [Commodity], [CandidateCount], [DecisionStatus], [SelectedSourceSystem], [SelectedObservationId], [SelectedRevision], [SelectedValueStd], [Reason], [CandidatesJson], [AuthorityPolicyVersion], [PublicationId])
        SELECT [DecisionId], [CanonicalKey], [StreamId], [WellId], [BusinessDate], [Commodity], [CandidateCount], [DecisionStatus], [SelectedSourceSystem], [SelectedObservationId], [SelectedRevision], [SelectedValueStd], [Reason], [CandidatesJson], [AuthorityPolicyVersion], [PublicationId] FROM lh_piep_core.serve.source_decision WHERE PublicationId = @PublicationId;

        DELETE FROM ops.publication WHERE PublicationId = @PublicationId;
        INSERT INTO ops.publication (PublicationId, BatchId, ParentBatchId, DatasetVersion, AuthorityPolicyVersion,
            MappingVersion, KpiContractVersion, UomFactorVersion, PeriodStart, PeriodEnd, ControlTotalsJson,
            BlockerCount, WarningCount, InfoCount, Status, StagedAtUtc, RunId)
        SELECT PublicationId, BatchId, ParentBatchId, DatasetVersion, AuthorityPolicyVersion, MappingVersion,
               KpiContractVersion, UomFactorVersion, PeriodStart, PeriodEnd, ControlTotalsJson,
               BlockerCount, WarningCount, InfoCount, 'APPROVAL_PENDING', @now, COALESCE(@RunId, RunId)
        FROM lh_piep_core.serve.publication_candidate
        WHERE PublicationId = @PublicationId;

        INSERT INTO ops.publication_event (PublicationId, EventType, Actor, Detail, EventAtUtc)
        SELECT PublicationId, 'SUPERSEDED_BEFORE_APPROVAL', 'system', CONCAT('Superseded by ', @PublicationId), @now
        FROM ops.publication
        WHERE Status = 'APPROVAL_PENDING' AND PublicationId <> @PublicationId;
        UPDATE ops.publication SET Status = 'SUPERSEDED', SupersededBy = @PublicationId
        WHERE Status = 'APPROVAL_PENDING' AND PublicationId <> @PublicationId;

        INSERT INTO ops.publication_event (PublicationId, EventType, Actor, Detail, EventAtUtc)
        VALUES (@PublicationId, 'STAGED', 'pipeline', CONCAT('Run ', COALESCE(@RunId, 'manual')), @now);
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH;

    SELECT PublicationId, Status, BlockerCount, WarningCount, InfoCount, ControlTotalsJson
    FROM ops.publication WHERE PublicationId = @PublicationId;
END;
GO

CREATE OR ALTER PROCEDURE ops.usp_approve_publication
    @PublicationId varchar(30),
    @Decision varchar(10) = 'APPROVE',
    @Comment varchar(1000) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @actor varchar(256) = CAST(SUSER_SNAME() AS varchar(256));
    DECLARE @now datetime2(6) = SYSUTCDATETIME();

    IF @Decision NOT IN ('APPROVE', 'REJECT')
        THROW 50020, 'Decision must be APPROVE or REJECT.', 1;
    IF NOT EXISTS (SELECT 1 FROM ops.authorized_approver
                   WHERE LOWER(ApproverUpn) = LOWER(@actor) AND IsActive = 1 AND DataDomain = 'PRODUCTION')
        THROW 50021, 'The current user is not an active authorized approver for PRODUCTION publications.', 1;
    IF NOT EXISTS (SELECT 1 FROM ops.publication WHERE PublicationId = @PublicationId AND Status = 'APPROVAL_PENDING')
        THROW 50022, 'Publication is not waiting for approval (check ops.vw_publication_history).', 1;

    BEGIN TRANSACTION;
    BEGIN TRY
        UPDATE ops.publication
        SET Status = CASE WHEN @Decision = 'APPROVE' THEN 'APPROVED' ELSE 'REJECTED' END,
            DecidedBy = @actor, DecidedAtUtc = @now, DecisionComment = @Comment
        WHERE PublicationId = @PublicationId;
        INSERT INTO ops.publication_event (PublicationId, EventType, Actor, Detail, EventAtUtc)
        VALUES (@PublicationId, CASE WHEN @Decision = 'APPROVE' THEN 'APPROVED' ELSE 'REJECTED' END, @actor,
                @Comment, @now);
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH;

    SELECT PublicationId, Status, DecidedBy, DecidedAtUtc FROM ops.publication WHERE PublicationId = @PublicationId;
END;
GO

CREATE OR ALTER PROCEDURE ops.usp_publish_publication
    @PublicationId varchar(30),
    @RunId varchar(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now datetime2(6) = SYSUTCDATETIME();

    IF EXISTS (SELECT 1 FROM ops.publication WHERE PublicationId = @PublicationId AND Status = 'PUBLISHED')
    BEGIN
        SELECT PublicationId, Status, PublishedAtUtc FROM ops.publication WHERE PublicationId = @PublicationId;
        RETURN;
    END;
    IF NOT EXISTS (SELECT 1 FROM ops.publication WHERE PublicationId = @PublicationId AND Status = 'APPROVED')
        THROW 50030, 'Publication is not APPROVED. Run ops.usp_approve_publication as an authorized approver first.', 1;

    BEGIN TRANSACTION;
    BEGIN TRY
        DELETE FROM gold.dim_date;
        INSERT INTO gold.dim_date ([DateKey], [Date], [Year], [MonthNumber], [MonthName], [YearMonth], [MonthStart], [DayOfMonth], [DaysInMonth], [PublicationId])
        SELECT [DateKey], [Date], [Year], [MonthNumber], [MonthName], [YearMonth], [MonthStart], [DayOfMonth], [DaysInMonth], [PublicationId] FROM stg.dim_date WHERE PublicationId = @PublicationId;
        DELETE FROM gold.dim_asset;
        INSERT INTO gold.dim_asset ([AssetKey], [AssetId], [AssetName], [CountryCode], [CountryName], [FacilityId], [PublicationId])
        SELECT [AssetKey], [AssetId], [AssetName], [CountryCode], [CountryName], [FacilityId], [PublicationId] FROM stg.dim_asset WHERE PublicationId = @PublicationId;
        DELETE FROM gold.dim_well;
        INSERT INTO gold.dim_well ([WellKey], [WellId], [WellName], [AssetKey], [AssetId], [CountryCode], [StreamId], [WellboreCount], [CompletionCount], [AliasList], [WellStatus], [PublicationId])
        SELECT [WellKey], [WellId], [WellName], [AssetKey], [AssetId], [CountryCode], [StreamId], [WellboreCount], [CompletionCount], [AliasList], [WellStatus], [PublicationId] FROM stg.dim_well WHERE PublicationId = @PublicationId;
        DELETE FROM gold.dim_equipment;
        INSERT INTO gold.dim_equipment ([EquipmentKey], [EquipmentId], [EquipmentName], [EquipmentType], [FacilityId], [AssetKey], [AssetId], [CountryCode], [PublicationId])
        SELECT [EquipmentKey], [EquipmentId], [EquipmentName], [EquipmentType], [FacilityId], [AssetKey], [AssetId], [CountryCode], [PublicationId] FROM stg.dim_equipment WHERE PublicationId = @PublicationId;
        DELETE FROM gold.dim_incident;
        INSERT INTO gold.dim_incident ([IncidentKey], [IncidentId], [IncidentCategory], [EventCount], [PublicationId])
        SELECT [IncidentKey], [IncidentId], [IncidentCategory], [EventCount], [PublicationId] FROM stg.dim_incident WHERE PublicationId = @PublicationId;
        DELETE FROM gold.dim_scenario;
        INSERT INTO gold.dim_scenario ([ScenarioKey], [ScenarioId], [ScenarioName], [PublicationId])
        SELECT [ScenarioKey], [ScenarioId], [ScenarioName], [PublicationId] FROM stg.dim_scenario WHERE PublicationId = @PublicationId;
        DELETE FROM gold.dim_cost_category;
        INSERT INTO gold.dim_cost_category ([CostCategoryKey], [CostCategory], [PublicationId])
        SELECT [CostCategoryKey], [CostCategory], [PublicationId] FROM stg.dim_cost_category WHERE PublicationId = @PublicationId;
        DELETE FROM gold.fact_production_daily;
        INSERT INTO gold.fact_production_daily ([DateKey], [WellKey], [AssetKey], [StreamId], [OilBbl], [GasMscf], [WaterBbl], [GrossBoe], [WiShare], [NetWiBoe], [ObservationCount], [ExpectedObservationCount], [IsComplete], [RetractedCount], [SelectedSources], [MaxRevision], [PublicationId])
        SELECT [DateKey], [WellKey], [AssetKey], [StreamId], [OilBbl], [GasMscf], [WaterBbl], [GrossBoe], [WiShare], [NetWiBoe], [ObservationCount], [ExpectedObservationCount], [IsComplete], [RetractedCount], [SelectedSources], [MaxRevision], [PublicationId] FROM stg.fact_production_daily WHERE PublicationId = @PublicationId;
        DELETE FROM gold.fact_target_daily;
        INSERT INTO gold.fact_target_daily ([DateKey], [AssetKey], [ScenarioKey], [TargetOilBbl], [TargetGasMscf], [TargetBoe], [PublicationId])
        SELECT [DateKey], [AssetKey], [ScenarioKey], [TargetOilBbl], [TargetGasMscf], [TargetBoe], [PublicationId] FROM stg.fact_target_daily WHERE PublicationId = @PublicationId;
        DELETE FROM gold.fact_operating_cost_monthly;
        INSERT INTO gold.fact_operating_cost_monthly ([MonthDateKey], [AssetKey], [CostCategoryKey], [CurrencyCode], [AmountLocal], [UsdPerUnit], [AmountUsd], [ClosingStatus], [CostId], [PublicationId])
        SELECT [MonthDateKey], [AssetKey], [CostCategoryKey], [CurrencyCode], [AmountLocal], [UsdPerUnit], [AmountUsd], [ClosingStatus], [CostId], [PublicationId] FROM stg.fact_operating_cost_monthly WHERE PublicationId = @PublicationId;
        DELETE FROM gold.fact_downtime_event;
        INSERT INTO gold.fact_downtime_event ([EventId], [IncidentKey], [EquipmentKey], [AssetKey], [StartDateKey], [StartUtc], [EndUtc], [DurationHours], [Reason], [PublicationId])
        SELECT [EventId], [IncidentKey], [EquipmentKey], [AssetKey], [StartDateKey], [StartUtc], [EndUtc], [DurationHours], [Reason], [PublicationId] FROM stg.fact_downtime_event WHERE PublicationId = @PublicationId;
        DELETE FROM gold.fact_loss_allocation;
        INSERT INTO gold.fact_loss_allocation ([LossId], [DateKey], [WellKey], [AssetKey], [IncidentKey], [EquipmentKey], [EventId], [LostOilBbl], [LostGasMscf], [LostBoeGross], [WiShare], [LostBoeNetWi], [ValueUsdGross], [ValueUsdNetWi], [PublicationId])
        SELECT [LossId], [DateKey], [WellKey], [AssetKey], [IncidentKey], [EquipmentKey], [EventId], [LostOilBbl], [LostGasMscf], [LostBoeGross], [WiShare], [LostBoeNetWi], [ValueUsdGross], [ValueUsdNetWi], [PublicationId] FROM stg.fact_loss_allocation WHERE PublicationId = @PublicationId;
        DELETE FROM gold.master_wellbore;
        INSERT INTO gold.master_wellbore ([WellboreId], [WellId], [WellboreName], [PublicationId])
        SELECT [WellboreId], [WellId], [WellboreName], [PublicationId] FROM stg.master_wellbore WHERE PublicationId = @PublicationId;
        DELETE FROM gold.master_completion;
        INSERT INTO gold.master_completion ([CompletionId], [WellboreId], [StreamId], [CompletionName], [PublicationId])
        SELECT [CompletionId], [WellboreId], [StreamId], [CompletionName], [PublicationId] FROM stg.master_completion WHERE PublicationId = @PublicationId;
        DELETE FROM gold.source_decision;
        INSERT INTO gold.source_decision ([DecisionId], [CanonicalKey], [StreamId], [WellId], [BusinessDate], [Commodity], [CandidateCount], [DecisionStatus], [SelectedSourceSystem], [SelectedObservationId], [SelectedRevision], [SelectedValueStd], [Reason], [CandidatesJson], [AuthorityPolicyVersion], [PublicationId])
        SELECT [DecisionId], [CanonicalKey], [StreamId], [WellId], [BusinessDate], [Commodity], [CandidateCount], [DecisionStatus], [SelectedSourceSystem], [SelectedObservationId], [SelectedRevision], [SelectedValueStd], [Reason], [CandidatesJson], [AuthorityPolicyVersion], [PublicationId] FROM stg.source_decision WHERE PublicationId = @PublicationId;

        -- Kontrol total: Gold harus sama persis dengan total yang dihitung nb_05
        DECLARE @expectedGross decimal(19,6), @actualGross decimal(19,6);
        SELECT @expectedGross = CAST(JSON_VALUE(ControlTotalsJson, '$.GrossBoe') AS decimal(19,6))
        FROM ops.publication WHERE PublicationId = @PublicationId;
        SELECT @actualGross = COALESCE(SUM(GrossBoe), 0) FROM gold.fact_production_daily;
        IF @expectedGross IS NULL OR @expectedGross <> @actualGross
            THROW 50031, 'Gold control total GrossBoe does not match the candidate manifest. Publication rolled back.', 1;

        INSERT INTO ops.publication_event (PublicationId, EventType, Actor, Detail, EventAtUtc)
        SELECT PublicationId, 'SUPERSEDED', 'system', CONCAT('Superseded by ', @PublicationId), @now
        FROM ops.publication WHERE Status = 'PUBLISHED';
        UPDATE ops.publication SET Status = 'SUPERSEDED', SupersededBy = @PublicationId WHERE Status = 'PUBLISHED';
        UPDATE ops.publication SET Status = 'PUBLISHED', PublishedAtUtc = @now
        WHERE PublicationId = @PublicationId;
        INSERT INTO ops.publication_event (PublicationId, EventType, Actor, Detail, EventAtUtc)
        VALUES (@PublicationId, 'PUBLISHED', 'pipeline', CONCAT('Run ', COALESCE(@RunId, 'manual')), @now);
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH;

    SELECT PublicationId, Status, PublishedAtUtc FROM ops.publication WHERE PublicationId = @PublicationId;
END;
GO

CREATE OR ALTER PROCEDURE ops.usp_sync_quality_evidence
    @BatchId varchar(10),
    @RunId varchar(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @now datetime2(6) = SYSUTCDATETIME();
    DECLARE @publicationId varchar(30) = CONCAT('PUB-', @BatchId);

    BEGIN TRANSACTION;
    BEGIN TRY
        DELETE FROM ops.quality_evidence WHERE BatchId = @BatchId;
        INSERT INTO ops.quality_evidence (BatchId, Stage, Status, PublicationId, BlockerCount, WarningCount,
            InfoCount, Message, RunId, UpdatedAtUtc, SyncedAtUtc)
        SELECT BatchId, Stage, Status, PublicationId, BlockerCount, WarningCount, InfoCount,
               LEFT(Message, 4000), RunId, UpdatedAtUtc, @now
        FROM lh_piep_core.ops.batch_status WHERE BatchId = @BatchId;

        DELETE FROM ops.dq_issue_summary WHERE BatchId = @BatchId;
        INSERT INTO ops.dq_issue_summary (BatchId, Stage, RuleId, Severity, IssueCount, SyncedAtUtc)
        SELECT BatchId, Stage, RuleId, Severity, COUNT(*), @now
        FROM lh_piep_core.ops.dq_issue WHERE BatchId = @BatchId
        GROUP BY BatchId, Stage, RuleId, Severity;

        IF EXISTS (SELECT 1 FROM ops.quality_evidence WHERE BatchId = @BatchId AND Status = 'QUALITY_FAILED')
           AND NOT EXISTS (SELECT 1 FROM ops.publication WHERE PublicationId = @publicationId)
        BEGIN
            INSERT INTO ops.publication (PublicationId, BatchId, BlockerCount, WarningCount, InfoCount, Status, RunId)
            SELECT @publicationId, @BatchId, BlockerCount, WarningCount, InfoCount, 'QUALITY_FAILED', @RunId
            FROM ops.quality_evidence WHERE BatchId = @BatchId AND Status = 'QUALITY_FAILED';
            INSERT INTO ops.publication_event (PublicationId, EventType, Actor, Detail, EventAtUtc)
            VALUES (@publicationId, 'QUALITY_FAILED', 'pipeline', 'Gold keeps the previous published publication', @now);
        END;
        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
        THROW;
    END CATCH;

    SELECT Stage, Status, BlockerCount, WarningCount, InfoCount FROM ops.quality_evidence
    WHERE BatchId = @BatchId ORDER BY UpdatedAtUtc;
END;
GO

CREATE OR ALTER PROCEDURE ops.usp_record_consumer_status
    @PublicationId varchar(30),
    @Consumer varchar(60),
    @Status varchar(30),
    @Detail varchar(1000) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DELETE FROM ops.consumer_status WHERE PublicationId = @PublicationId AND Consumer = @Consumer;
    INSERT INTO ops.consumer_status (PublicationId, Consumer, Status, Detail, UpdatedAtUtc)
    VALUES (@PublicationId, @Consumer, @Status, @Detail, SYSUTCDATETIME());
END;
GO
