-- Generated by `python -m workshop render-warehouse`. Seed kontrak KPI dan approver.
-- Ganti <APPROVER_UPN> dengan UPN Microsoft Entra pemilik data produksi (business owner) sebelum menjalankan.
-- Versi kebijakan: authority SA-2025.1, mapping PPDM-ALIGN-1.0, KPI KPI-1.0.

DELETE FROM ops.kpi_contract WHERE ContractVersion = 'KPI-1.0';
INSERT INTO ops.kpi_contract (KpiId, KpiName, Definition, Unit, Grain, DataOwner, SourceColumn, ContractVersion)
VALUES
    ('KPI-01', 'Gross production (BOE)', 'Oil bbl + Gas Mscf / 6 for the selected authoritative value of each stream-day', 'BOE', 'Reporting stream x day', 'Production Reporting', 'fact_production_daily.GrossBoe', 'KPI-1.0'),
    ('KPI-02', 'Net WI production (BOE)', 'Gross BOE x working interest effective on the business date', 'BOE', 'Reporting stream x day', 'Production Reporting', 'fact_production_daily.NetWiBoe', 'KPI-1.0'),
    ('KPI-03', 'Target achievement (%)', 'Gross BOE / Target BOE for the same asset and dates', '%', 'Asset x day', 'Planning (RKAP)', 'fact_target_daily.TargetBoe', 'KPI-1.0'),
    ('KPI-04', 'Data completeness (%)', 'Stream-days with Oil, Gas and Water / all stream-days in period', '%', 'Reporting stream x day', 'Data Management', 'fact_production_daily.IsComplete', 'KPI-1.0'),
    ('KPI-05', 'Production loss (BOE)', 'Approved loss allocation, gross and net WI', 'BOE', 'Well x day x event', 'Operations', 'fact_loss_allocation.LostBoeGross', 'KPI-1.0'),
    ('KPI-06', 'Opex (USD)', 'Closing operating cost converted with the approved monthly FX rate', 'USD', 'Asset x month x category', 'Finance', 'fact_operating_cost_monthly.AmountUsd', 'KPI-1.0'),
    ('KPI-07', 'Equipment downtime (hours)', 'Sum of downtime event duration', 'hours', 'Event', 'Operations', 'fact_downtime_event.DurationHours', 'KPI-1.0');
GO

DELETE FROM ops.authorized_approver WHERE ApproverUpn = '<APPROVER_UPN>';
INSERT INTO ops.authorized_approver (ApproverUpn, ApproverRole, DataDomain, IsActive)
VALUES ('<APPROVER_UPN>', 'Production data owner (workshop)', 'PRODUCTION', 1);
GO

-- Cek: hasilnya harus sama dengan UPN Anda agar usp_approve_publication mengizinkan approval
SELECT SUSER_SNAME() AS CurrentUser, ApproverUpn, IsActive FROM ops.authorized_approver;
GO
